apiVersion: apps/v1
kind: Deployment
metadata:
  name: accelq-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accelq-agent
  template:
    metadata:
      labels:
        app: accelq-agent
    spec:
      containers:
      - name: accelq-agent
        image: ine1dvidk8.azurecr.io/accelq/agent:latest
        ports:
          - containerPort: 1433
          - containerPort: 8433
        resources:
          limits:
            memory: "6Gi"
            cpu: "1"
