apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsts-agent
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vsts-agent
  template:
    metadata:
      labels:
        app: vsts-agent
    spec:
      containers:
      - name: vsts-agent
        image: __DOCKER_IMAGE__
        env:
          - name: VSTS_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: vsts
                key: VSTS_ACCOUNT
          - name: VSTS_TOKEN
            valueFrom:
              secretKeyRef:
                name: vsts
                key: VSTS_TOKEN
          - name: VSTS_POOL
            value: __VSTS_POOL__
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
